import type { KnipConfig } from 'knip'

/**
 * Knip configuration for dead code detection.
 *
 * Electron has no knip plugin — entry points are specified manually.
 * Proto-components (P3-P5) and pre-installed shadcn UI components
 * are ignored until they are wired into the app.
 *
 * Export checking is excluded: shadcn's barrel-export pattern and
 * Redux future-phase actions create too much noise. Re-enable when
 * all proto-components are integrated.
 *
 * @example
 *   pnpm knip        // Run dead code analysis
 *   pnpm knip --fix  // Auto-remove unused exports (use with caution)
 */
const config: KnipConfig = {
  entry: [
    // App entry
    'src/App.tsx',

    // Electron (no knip plugin)
    'electron/main.ts',
    'electron/preload.ts',
    'electron/test-auth.ts',
  ],

  project: ['src/**/*.{ts,tsx}', 'electron/**/*.ts', 'scripts/**/*.ts'],

  ignore: [
    // Build artifacts
    'dist/**',
    'dist-electron/**',
    'coverage/**',

    // Generated by RTK Query codegen
    'src/store/api/raindropApi.ts',

    // Proto-components for future phases (P3-P5)
    'src/components/raindrop/color-picker.tsx',
    'src/components/raindrop/directory-view.tsx',
    'src/components/raindrop/drag-preview.tsx',
    'src/components/raindrop/drop-indicator.tsx',
    'src/components/raindrop/icon-picker.tsx',
    'src/components/raindrop/table-view.tsx',
    'src/components/raindrop/tag-input.tsx',

    // Pre-installed shadcn UI components (not yet consumed)
    'src/components/ui/accordion.tsx',
    'src/components/ui/avatar.tsx',
    'src/components/ui/combobox.tsx',
    'src/components/ui/context-menu.tsx',
    'src/components/ui/field.tsx',
    'src/components/ui/hover-card.tsx',
    'src/components/ui/progress.tsx',
    'src/components/ui/radio-group.tsx',
    'src/components/ui/resizable.tsx',
    'src/components/ui/slider.tsx',
    'src/components/ui/table.tsx',
    'src/components/ui/tabs.tsx',
    'src/components/ui/toggle-group.tsx',
    'src/components/ui/toggle.tsx',

    // DnD utility types (used by ignored proto-components)
    'src/utils/dnd-types.ts',
  ],

  // Exclude export/type checking — shadcn barrel-exports + Redux
  // future-phase actions make this too noisy at current project stage.
  // Focus on file and dependency detection (highest value).
  exclude: ['exports', 'types', 'nsExports', 'nsTypes'],

  ignoreDependencies: [
    // CSS-only imports (not statically detectable by JS analysis)
    'tw-animate-css',
    '@fontsource-variable/geist',

    // CLI-only tool (npx shadcn add ...)
    'shadcn',

    // Future-phase runtime dependencies (P3-P5, listed in SPEC.md)
    '@base-ui/react',
    '@dnd-kit/core',
    '@dnd-kit/sortable',
    '@dnd-kit/utilities',
    'date-fns',
    'fuse.js',
    'motion',
    'react-day-picker',
    'react-resizable-panels',
    'ts-pattern',

    // DevDeps: CLI/build tools not imported in source
    '@faker-js/faker',
    'electron-builder',
    'esbuild-runner',

    // DevDeps: peer deps of eslint-config-ts-prefixer
    'globals',
    'typescript-eslint',

    // Used in test/mocks but knip can't trace vitest setupFiles → msw
    'msw',
  ],
}

export default config
